### ISSUE TITLE
CloudFlare has broke the script.

### ISSUE THREAD

**Issue by skid9000** [skid9000/CrunchyrollAuth#1]
~~Welp, it seems that Crunchyroll has changed somthing in their login method~~ ...

~~I don't know yet what has been changed but i will update here if i find something ...~~

*EDIT* : https://github.com/skid9000/CrunchyrollAuth/issues/1#issuecomment-412377092

![](https://puush.tuto-craft.com/1V9O6o.png)

**Comment by bc1bb** [comment]
503 means that it's temporary

**Comment by skid9000** [comment]
It has been more than a week that i got the problem so i do think that something has changed.

Now that i think about it, maybe the 503 is returned by Cloudflare ... I need to check that ...

**Comment by bc1bb** [comment]
Ok

**Comment by skid9000** [comment]
Ok so i investigated a little and it seems like Cloudflare has added some crappy protections to login pages ...

https://github.com/rg3/youtube-dl/issues/17116#issuecomment-410794554

So i need to see how can i solve that ...

**Comment by ghost** [comment]
Fuck CloudFlare. (found this on mastodon and just wanted to throw that real quick kthxbye)

**Comment by jofeju** [comment]
Any news...?

**Comment by skid9000** [comment]
I'm still searching how to solve the cloudflare checks ....

In the meantime, you can generate the cookies.txt from your web browser and export it in the netscape format.

If you are a user of Crunchyroll Downloader, just put the cookie file in C:\ProgramData\Crunchy-DL

**Comment by jofeju** [comment]
Thx, it works.

**Comment by skid9000** [comment]
OK, i think i solved the problem with cfscrape!

I will deploy that ASAP.

**Comment by skid9000** [comment]
Fixed ! :D
